Test:
  access:
    site:
      login: true
    admin:
      login: true
      super: false
      cache: false
      configuration: false
      pages: true
      maintenance: false
      statistics: false
      plugins: false
      themes: false
      tools: false
      users: false
      flex-objects: false
  readableName: Test
  enabled: true
User:
  access:
    site:
      login: true
    admin:
      login: true
      super: false
      cache: true
      configuration: false
      pages: true
      maintenance: false
      statistics: false
      plugins: false
      themes: false
      tools: false
      users: false
      flex-objects: false
  readableName: User
  enabled: true
Fanzine:
  access:
    site:
      login: true
    admin:
      login: true
      super: false
      cache: true
      configuration: false
      pages: true
      maintenance: false
      statistics: false
      plugins: false
      themes: false
      tools: false
      users: false
      flex-objects: false
  readableName: Fanzine
  enabled: true
